### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by schoettl** [docopt/docopt.hs#13]
I try for days and don't get it work:

How to access an argument of an option (`... --out=file ...`)?

I copied the first example from [Hackage](https://hackage.haskell.org/package/docopt-0.7.0.1/docs/System-Console-Docopt.html) and added an argument to the option `--caps`. Then I added three lines at the bottom of the `main`.

I run the program and get an error:
```
$ ./program echo --caps=test hallo
HALLO
argument expected for: Argument "test"


docopt-sample version 0.1.0

Usage:
  docopt-sample cat <file>
  docopt-sample echo [--caps=<test>] <string>

Options:
  -c, --caps=<test>    Caps-lock the echoed argument
```

 * [My changes from the Hackage example above](https://github.com/schoettl/computationalgeometry_2/commit/45be04c991eb45ab6527b857fe06f3b9de5caf83)
 * [Full code at GitHub](https://github.com/schoettl/computationalgeometry_2/blob/45be04c991eb45ab6527b857fe06f3b9de5caf83/haskell/Main.hs)

Maybe it's a trivial error and anyone can help me?

**Comment by ryanartecona** [comment]
Sorry you've had trouble with it! The good news is it's an easy fix. :)

On [this line](https://github.com/schoettl/computationalgeometry_2/commit/45be04c991eb45ab6527b857fe06f3b9de5caf83#diff-99bf3b5bac4d48b236996cd382d0dca5R38), change `argument "test"` to `longOption "caps"`. When you have an option like `--caps=<test>`, the `<test>` part only serves to communicate that `--caps` expects an argument, and is otherwise ignored. The `argument expected for:...` message is what `getArgOrExitWith` does when its lookup fails.

Maybe cases like this should treat the `<test>` as a synonym with `--caps`, as in the argument can be looked up with either `argument` or `longOption`? I'll think about this a bit. At the very least, this could be clearer in the docs.

**Comment by schoettl** [comment]
Ahh. Thank you!

If it is not really trivial to "treat the `<test>` as a synonym with `--caps`", it's probably not worth the effort.

One problem that can occur, when trying to fix this, are name collisions. Example:
```
usage:
  program [options] FILE
options:
  --offset N  offset in the file
  --bytes N   number of bytes
  --output FILE  the output file
```
Especially in large usage messages, this can happen. Sure, the developer can avoid this, but then he really have to read the Docopt documentation! And priorization for this case is not really obvious to a new developer.

An example how to use options with arguments in the [README](https://github.com/docopt/docopt.hs/blob/master/README.md) would be great and helpful.

**Comment by ryanartecona** [comment]
Well, [I did, earlier today](https://github.com/docopt/docopt.hs/commit/59f3af0c045918b2ca1ca439a94b51d56ffec54b#diff-04c6e90faac2675aa89e2176d2eec7d8R105). :) Do you think that's enough, or that it should be more prominent? Or rather, do you think that that would've been enough to point you in the right direction if it had been in the README before?

**Comment by schoettl** [comment]
I commented your commit.

**Comment by ryanartecona** [comment]
Thanks for that. I'll make those changes, and also update the haddock documentation to make note of this case.

**Comment by ryanartecona** [comment]
Take a look at 7283baa and see if that will work. I made the changes you suggested, and also added notes along side the haddock descriptions of the `argument` and `longOption`/`shortOption` functions.

I'd like to eventually have everything that's currently in the README instead in a `System.Console.Docopt.Tutorial` module, so that all the documentation can be had without leaving hackage, and also locally if the package's docs are compiled when it's installed. 

Let me know (open more issues) if anything else sticks out that could be made clearer! Otherwise, feel free to close this issue, and I'll upload the new docs to hackage.

**Comment by schoettl** [comment]
Thanks for your commitment :)

And I added two comments on [your commit](https://github.com/docopt/docopt.hs/commit/7283baaf00707149073d42e7ece099e39d9ca540).

**Comment by ryanartecona** [comment]
@schoettl Thanks for taking the time to help me improve the docs!

I've been busy for the last week, but I just (hopefully) clarified that weird sentence in the README in 0686e2d, and updated the docs in Hackage at v.0.7.0.2 with notes that will help others avoid your problem case. :beers:
