### ISSUE TITLE
Options aren't found if some options but not `[options]` are allowed elsewhere

### ISSUE THREAD

**Issue by alexchandel** [docopt/docopt.hs#17]
Consider the usage:
```
Usage:
  foo [-v] <bar>
  foo --help

Options:
  -h, --help        Print this message.
  -v, --verbose     Print extra warnings and information.
```

When invoked as `foo --help`, `(isPresent args (longOption "help"))` always returns false. However, if `[-v]` is changed to `[options]` OR deleted altogether, then it works as expected.

**Comment by ryanartecona** [comment]
For this particular usage, you'll need to have the `foo --help` line come before the other one.

This is a symptom of the greediness of positional arguments, e.g. `<bar>` here. They will match anything, like a `.*` in a regex, so you have to take care that they _don't_ match when you don't want them to. Here, since the `-v` is optional, the `<bar>` is greedily matching the first argument to `foo`, _no matter what it is_. When you change `[-v]` to `[options]`, the `[options]` successfully matches the `--help` that you gave it, and since there's no second argument to match the `<bar>` that comes after, the pattern fails and falls through to the second pattern, `foo --help`, which succeeds.

To be clear, this gotcha is a pretty regular source of confusion with all the `docopt` ports, since it's inherent in the semantics of the patterns and argument types.

Feel free to close if this clears things up for you!
