### ISSUE TITLE
Make docopt insensitive to the ordering of options

### ISSUE THREAD

**Issue by rubik** [docopt/docopt.hs#24]
I know that at the end of README it's clearly written that this implementation is order-sensitive. But I think that should be changed, as it forces me to write all the permutations of the options, which is quite boring and absolutely not DRY.
Moreover, it's confusing to the user, which in `--help` sees a lot of very similar invocations.

**Comment by ryanartecona** [comment]
Can you give an example of a usage which is painful? I can probably give you suggestions, but it's much easier to talk over examples :)

**Comment by ryanartecona** [comment]
Oh, oops. I didn't see the referring issue. That case can probably be handled by using an `[options]`, if you'd like to allow any option in that place, or by defining single-character aliases for the options you want there, and then giving them in the usage like so:

```
Usage:
  argon [-mn]... <dir>

Options:
  -m <min>, --min <min>  A minimum.
  -n, --no-color         Don't colorize output.
```

Does that help?

**Comment by rubik** [comment]
Thanks for the help. Since I don't need a single character alias for `--no-color` I'll try `[options]`, it probably does what I want.

**Comment by rubik** [comment]
I have a new problem, related to this one. I have to add a new option, -I --include that can be specified multiple times. I tried the following usage, but the options are not grouped:
```
Usage:
    argon [options] <paths>...

Options:
    -h --help               show this help
    -m --min=<n>            the minimum complexity to show in results
    -I --include=<path>     additional header files for the C preprocessor
    --no-color              results are not colored
    -j --json               results are serialized to JSON
```

I'd like to be able to do

    $ argon -I path/to/header -I path/to/second/header -m6 src app

where `include=['path/to/header', 'path/to/second/header']`, `min=6`, `paths=['src', 'app']`. How does one accomplishes this?

**Comment by ryanartecona** [comment]
Huh, that looks slightly different. I'd expect that to work as you expected
also.

I think this is a bug by itself, but there may be away around it for the
time being. What happens if you change `[options]` to `[options]...`?

On Mon, Nov 2, 2015 at 11:56 AM, Michele Lacchia <notifications@github.com>
wrote:

> I have a new problem, related to this one. I have to add a new option, -I
> --include that can be specified multiple times. I tried the following
> usage, but the options are not grouped:
>
> Usage:
>     argon [options] <paths>...
>
> Options:
>     -h --help               show this help
>     -m --min=<n>            the minimum complexity to show in results
>     -I --include=<path>     additional header files for the C preprocessor
>     --no-color              results are not colored
>     -j --json               results are serialized to JSON
>
> I'd like to be able to do
>
> $ argon -I path/to/header -I path/to/second/header -m6 src app
>
> where include=['path/to/header', 'path/to/second/header'], min=6, paths=['src',
> 'app']. How does one accomplishes this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docopt/docopt.hs/issues/24#issuecomment-153082237>.
>



-- 
Ryan Artecona

**Comment by rubik** [comment]
Then it interprets (oddly) everything as a positional argument (paths).

**Comment by schoettl** [comment]
Hi, I think this issue should be re-opened. **Options should be order-independent.** At least, if they are all at the same side of a positional argument or a command. That is almost standard for command line options. I don't know any Unix program that disallow `prog -a -b` but allow `prog -b -a`. For me, that is just a bug.

@ryanartecona, you offered help to work around. My example is this:

```
usage:
  orgly [-io] --list
  orgly [-io] --title=TITLE...
  orgly --help
```

I could formulate it as:

```
usage:
  orgly [options] list
  orgly [options] make-titles TITLE...
  orgly --help
```

But a good command line arg parser should not force me to do so, right? Take `pacman` or `dpkg`: They also have options that specify the command (e.g. `pacman -S` for install and `pacman -Q` for query).

The problem with the second way in my case is this: I have an alias that chains `orgly --list | fzf | xargs1 orgly --title={}` and I would like to be able call `myalias -o outputfile`. This fails because options are order-sensitive.
