### ISSUE TITLE
Bump upper bound of template-haskell.

### ISSUE THREAD

**Issue by Xitian9** [docopt/docopt.hs#45]
Currently the cabal file specifies it requires template-haskell < 2.16, while the most recent version on hackage is 2.17. Can the version just be bumped, or is there an actual incompatibility to sort out?

**Comment by Xitian9** [comment]
Just bumping the bounds on my system seems to work. I'll submit a PR.

**Comment by FullstackGJJ** [comment]
Sounds good, I'm running into a conundrum because I was recently informed that specific versions of template haskell are tied to specific versions of GHC. That seems to be causing problems with backwards compatibility and future advancements as people want to move onto newer versions of GHC over time.

**Comment by FullstackGJJ** [comment]
#44 has been merged. Resolving this specific request.
