### ISSUE TITLE
Release new version once recent merges are tested

### ISSUE THREAD

**Issue by Minoru** [docopt/docopt.hs#6]
Well, this is it: do not forget to release 0.7 (or whatever) once merges are tested and verified.

**Comment by ryanartecona** [comment]
So, even with this thoughtful and helpful open issue, I still managed to let this slip. :worried: :sweat_drops: I left this in my inbox when I returned from that trip last summer, and meant to get to it once I settled into my new job. I think I accidentally deleted the email somehow, and quickly forgot about it.

I released this just now as [0.6.0.2](https://hackage.haskell.org/package/docopt-0.6.0.2), since the docs here in master had been out-of-sync with the hackage version since then anyway.

Thanks again for your help with this last summer @Minoru!
